"""make unread_message_count dynamic

Revision ID: 39b8c2651951
Revises: 5659396cc0db
Create Date: 2025-03-16 19:32:53.658103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39b8c2651951'
down_revision = '5659396cc0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('unread_message_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_message_count', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
