"""add sequence field to text_segments table

Revision ID: 3a839a8054a9
Revises: b76205e5aeb2
Create Date: 2025-03-16 21:34:01.453331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a839a8054a9'
down_revision = 'b76205e5aeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_segments', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
