"""Add company table

Revision ID: 50a38384e6d5
Revises: 8a80412ad51d
Create Date: 2025-04-03 00:42:21.607984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50a38384e6d5'
down_revision = '8a80412ad51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_memory_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['translation_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    op.drop_table('translation_memory_entries')
    # ### end Alembic commands ###
