"""Add ad term-unit table

Revision ID: 8050b5b50d78
Revises: abfdefd0e0f0
Create Date: 2025-03-24 16:53:07.519674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8050b5b50d78'
down_revision = 'abfdefd0e0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_term', sa.String(length=255), nullable=False),
    sa.Column('target_term', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('termbase_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['termbase_id'], ['termbases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms')
    # ### end Alembic commands ###
