"""Add advertisement table

Revision ID: 86b42fd6c2e0
Revises: 3a839a8054a9
Create Date: 2025-03-17 16:18:56.637970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b42fd6c2e0'
down_revision = '3a839a8054a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('redirect_url', sa.String(length=512), nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=False),
    sa.Column('remaining_clicks', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'UNDER_REVIEW', 'REJECTED', name='adstatus'), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_phone'], ['users.phone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisements')
    # ### end Alembic commands ###
