"""add is_translating field to documents table

Revision ID: b76205e5aeb2
Revises: 1d28cf828099
Create Date: 2025-03-16 21:21:22.383534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76205e5aeb2'
down_revision = '1d28cf828099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_translating', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('is_translating')

    # ### end Alembic commands ###
