"""Add consumption record table

Revision ID: e346569a185f
Revises: 86b42fd6c2e0
Create Date: 2025-03-17 16:22:06.260726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e346569a185f'
down_revision = '86b42fd6c2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=False),
    sa.Column('ad_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('consumption_time', sa.DateTime(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('consumption_type', sa.Enum('NEW_AD', 'RECHARGE', name='consumptiontype'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['advertisements.id'], ),
    sa.ForeignKeyConstraint(['user_phone'], ['users.phone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumption_records')
    # ### end Alembic commands ###
